### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by fanruifeng** [gaussic/text-classification-cnn-rnn#127]
训练时 到 epoch 1的时候, 报错, 
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node cnn/conv/conv1d/Conv2D (defined at E:\text-classification-cnn-rnn-master\cnn_model.py:50)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cnn/conv/conv1d/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, cnn/conv/conv1d/ExpandDims_1)]]
	 [[{{node optimize/Mean/_11}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_63_optimize/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
大家如果解决了 , 麻烦告诉下 谢谢  qq:1125729232

**Comment by xieqibin003** [comment]
我也碰到同样的问题了，我百度了说了cudnn的版本和tensorflow的版本不一致，但是我的cudnn的是7.4.2的，应该没问题吧？楼上的兄弟如果解决了麻烦留言一下哈

**Comment by StarZhai** [comment]
https://www.cnblogs.com/StarZhai/p/tensorflow-gpu.html
我是按照这个链接配置的GPU环境，运行这个项目没问题。你可以参考试试

**Comment by prozyworld** [comment]
win10下 用pycharm tensorflow-gpu 和 cuda 以及 cudnn版本对应上 什么都不用配置 版本对应可以参考官网https://www.tensorflow.org/install/source_windows 还有深度不够的话gpu版本不见得比cpu快 可以都尝试对比一下
